### ISSUE TITLE
Update Sigstore Roadmap

### ISSUE THREAD

**Issue by tracymiranda** [sigstore/community#472]
The Sigstore roadmap had its last noteworthy update in September 2023. 
There have been a bunch of significant changes since then worth adding, including highlights mentioned in this talk https://www.youtube.com/watch?v=8Kwuo21kAaI

This PR tracks making updates to bring roadmap upto date, including

- [ ] Update current status & programming language
- [ ] Update ecosystem adoption
- [ ] Update project roadmap to reflect recent advancements
